/*
============================================================
PROJECT : Sales Analytics
MODULE  : Executive Dashboard
DESCRIPTION:
This module analyzes the overall sales performance of the
company by evaluating key executive-level business KPIs.
============================================================
*/


/*
============================================================
KPI 1 : Total Revenue

Business Objective:
Measure the total revenue generated by the company during
the analysis period to evaluate overall business performance.
============================================================
*/

SELECT
    ROUND(SUM(sales),2) AS total_revenue
FROM Order_Details;



/*
============================================================
KPI 2 : Total Orders

Business Objective:
Determine the total number of customer orders placed to
measure overall sales activity.
============================================================
*/

SELECT
    COUNT(*) AS total_orders
FROM Orders;



/*
============================================================
KPI 3 : Active Customers

Business Objective:
Identify the number of unique customers who placed at least
one order during the analysis period.
============================================================
*/

SELECT
    COUNT(DISTINCT customer_id) AS total_customers
FROM Orders;



/*
============================================================
KPI 4 : Average Order Value (AOV)

Business Objective:
Calculate the average revenue generated per order to
understand customer purchasing behavior.
============================================================
*/

SELECT

    ROUND(
        SUM(sales) /
        COUNT(DISTINCT order_number),
    2) AS average_order_value

FROM Order_Details;



/*
============================================================
KPI 5 : Annual Revenue Performance

Business Objective:
Identify the highest revenue generating year to evaluate
business growth over time.
============================================================
*/

SELECT

    YEAR(o.order_date) AS sales_year,

    ROUND(
        SUM(od.sales),
    2) AS total_revenue

FROM Orders o

JOIN Order_Details od
ON o.order_number = od.order_number

GROUP BY YEAR(o.order_date)

ORDER BY total_revenue DESC;



/*
============================================================
KPI 6 : Quarterly Revenue Performance

Business Objective:
Analyze quarterly sales performance to identify seasonal
revenue patterns throughout the year.
============================================================
*/

SELECT

    YEAR(o.order_date) AS sales_year,

    QUARTER(o.order_date) AS sales_quarter,

    ROUND(
        SUM(od.sales),
    2) AS total_revenue

FROM Orders o

JOIN Order_Details od
ON o.order_number = od.order_number

GROUP BY

    YEAR(o.order_date),

    QUARTER(o.order_date)

ORDER BY

    sales_year,

    total_revenue DESC;



/*
============================================================
KPI 7 : Monthly Revenue Performance

Business Objective:
Determine the highest revenue generating month each year
to identify seasonal demand patterns.
============================================================
*/

SELECT

    YEAR(o.order_date) AS sales_year,

    MONTH(o.order_date) AS sales_month,

    MONTHNAME(o.order_date) AS month_name,

    ROUND(
        SUM(od.sales),
    2) AS total_revenue

FROM Orders o

JOIN Order_Details od
ON o.order_number = od.order_number

GROUP BY

    YEAR(o.order_date),

    MONTH(o.order_date),

    MONTHNAME(o.order_date)

ORDER BY

    sales_year,

    total_revenue DESC;



/*
============================================================
KPI 8 : Monthly Revenue Trend

Business Objective:
Track monthly revenue over time to understand overall
sales trends and identify seasonal fluctuations.
============================================================
*/

SELECT

    YEAR(o.order_date) AS sales_year,

    MONTH(o.order_date) AS sales_month,

    MONTHNAME(o.order_date) AS month_name,

    ROUND(
        SUM(od.sales),
    2) AS total_revenue

FROM Orders o

JOIN Order_Details od
ON o.order_number = od.order_number

GROUP BY

    YEAR(o.order_date),

    MONTH(o.order_date),

    MONTHNAME(o.order_date)

ORDER BY

    sales_year,

    sales_month;



/*
============================================================
KPI 9 : Month-over-Month Sales Growth

Business Objective:
Measure monthly sales growth by comparing each month's
revenue with the previous month to identify business
growth and decline trends.
============================================================
*/

WITH MonthlyRevenue AS
(
    SELECT

        YEAR(o.order_date) AS sales_year,

        MONTH(o.order_date) AS sales_month,

        MONTHNAME(o.order_date) AS month_name,

        SUM(od.sales) AS total_revenue

    FROM Orders o

    JOIN Order_Details od
    ON o.order_number = od.order_number

    GROUP BY

        YEAR(o.order_date),

        MONTH(o.order_date),

        MONTHNAME(o.order_date)
),

RevenueComparison AS
(
    SELECT

        sales_year,

        sales_month,

        month_name,

        ROUND(total_revenue,2) AS current_month_revenue,

        LAG(total_revenue)
        OVER(
            ORDER BY sales_year,sales_month
        ) AS previous_month_revenue

    FROM MonthlyRevenue
)

SELECT

    sales_year,

    month_name,

    current_month_revenue,

    ROUND(previous_month_revenue,2) AS previous_month_revenue,

    ROUND(
        (
            current_month_revenue -
            previous_month_revenue
        )
        /
        NULLIF(previous_month_revenue,0)
        *100,
    2) AS growth_percentage,

    CASE

        WHEN previous_month_revenue IS NULL
            THEN 'N/A'

        WHEN current_month_revenue > previous_month_revenue
            THEN 'Growing'

        WHEN current_month_revenue < previous_month_revenue
            THEN 'Declining'

        ELSE 'Stable'

    END AS trend

FROM RevenueComparison;



/*
============================================================
KPI 10 : Revenue Contribution by Country

Business Objective:
Identify the countries generating the highest revenue to
understand the company's strongest geographical markets.
============================================================
*/

SELECT

    c.country,

    ROUND(
        SUM(od.sales),
    2) AS total_revenue

FROM Orders o

JOIN Order_Details od
ON o.order_number = od.order_number

JOIN Customers c
ON o.customer_id = c.customer_id

GROUP BY
    c.country

ORDER BY
    total_revenue DESC;